name: Generate Exercise Index

on:
  push:
    branches:
      - main
    paths:
      - 'data/**'
  workflow_dispatch:

jobs:
  generate-index:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate index.json
        run: |
          echo "Generating index.json from data directory..."
          cd data
          ls *.json | sed 's/.json$//' > ../filelist.txt
          cd ..
          
          # Create JSON array from file list
          echo "[" > index.json
          first=true
          while IFS= read -r filename; do
            if [ "$first" = true ]; then
              echo "  \"$filename\"" >> index.json
              first=false
            else
              echo "  ,\"$filename\"" >> index.json
            fi
          done < filelist.txt
          echo "]" >> index.json
          
          rm filelist.txt
          
          echo "Generated index.json with $(cat index.json | grep -c '\"') files"
          cat index.json
      
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add index.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-generate exercise index" && git push)
