name: Process Exercise Submission

on:
  issues:
    types: [opened]

jobs:
  process-submission:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'exercise-submission')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract JSON from issue
        id: extract
        uses: actions/github-script@v6
        with:
          script: |
            const issueBody = context.payload.issue.body;
            
            // Extract JSON between ```json and ```
            const jsonMatch = issueBody.match(/```json\s*\n([\s\S]*?)\n```/);
            
            if (!jsonMatch) {
              core.setFailed('Could not find JSON in issue body');
              return;
            }
            
            const jsonData = jsonMatch[1];
            
            // Generate filename
            const timestamp = Date.now();
            const filename = `exercise_${timestamp}.json`;
            
            // Write file to repository
            const fs = require('fs');
            fs.writeFileSync(`data/${filename}`, jsonData);
            
            core.setOutput('filename', filename);
            
            return filename;
      
      - name: Commit exercise file
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/*.json
          git commit -m "Add exercise from issue #${{ github.event.issue.number }}"
          git push
      
      - name: Close issue with success message
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ **Exercise successfully added to the database!**\n\nYour exercise has been processed and committed to the repository. It will appear on the website once the index is regenerated (usually within a minute).\n\nThank you for your contribution! 🎉'
            });
            
            github.rest.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed'
            });
